#!/usr/bin/env bash
# Generate Prometheus SLO rules from Sloth specs and package them as PrometheusRule
# resources for the Prometheus Operator (kube-prometheus-stack, Phase 2+).
#
#   slos/*.yaml  --(sloth)-->  observability/prometheus/rules/*.yaml  --(promtool check)-->
#   observability/prometheus/slo-prometheusrules.yaml  (kind: PrometheusRule, one per service)
#
# Requires only Docker. Usage: scripts/gen-slo-rules.sh   (or: make slo-rules, which also applies it)
set -euo pipefail
cd "$(dirname "$0")/.."

SLOTH_IMAGE="ghcr.io/slok/sloth:v0.16.0"
PROM_IMAGE="prom/prometheus:v3.14.0"   # same version as the bundled Prometheus
RULES_DIR="observability/prometheus/rules"
OUT="observability/prometheus/slo-prometheusrules.yaml"
NAMESPACE="observability"

mkdir -p "$RULES_DIR"
rm -f "$RULES_DIR"/*.yaml

echo "==> Generating rules with Sloth"
docker run --rm -v "$PWD:/w" -w /w "$SLOTH_IMAGE" generate -i slos -o "$RULES_DIR" --no-log

echo "==> Validating rules with promtool"
docker run --rm -v "$PWD/$RULES_DIR:/r" --entrypoint promtool "$PROM_IMAGE" \
  check rules $(cd "$RULES_DIR" && ls *.yaml | sed 's|^|/r/|')

echo "==> Packaging rules as PrometheusRule resources -> $OUT"
python3 - "$RULES_DIR" "$OUT" "$NAMESPACE" <<'PY'
import glob, os, sys, yaml
rules_dir, out, ns = sys.argv[1:4]
docs = []
for f in sorted(glob.glob(os.path.join(rules_dir, "*.yaml"))):
    groups = [g for d in yaml.safe_load_all(open(f)) if d and "groups" in d for g in d["groups"]]
    svc = os.path.splitext(os.path.basename(f))[0]
    docs.append({"apiVersion": "monitoring.coreos.com/v1", "kind": "PrometheusRule",
                 "metadata": {"name": f"slo-{svc}", "namespace": ns,
                              "labels": {"app.kubernetes.io/part-of": "sre-lab", "sre-lab/type": "slo"}},
                 "spec": {"groups": groups}})
with open(out, "w") as fh:
    fh.write("# GENERATED by scripts/gen-slo-rules.sh from slos/*.yaml. DO NOT EDIT.\n")
    yaml.safe_dump_all(docs, fh, sort_keys=False, width=200)
n = sum(len(g["rules"]) for d in docs for g in d["spec"]["groups"])
print(f"   {len(docs)} PrometheusRules, {n} rules")
PY
