#!/usr/bin/env bash
# Generate Prometheus SLO rules from Sloth specs and package them as Helm values
# for the bundled Prometheus in the opentelemetry-demo chart.
#
#   slos/*.yaml  --(sloth)-->  observability/prometheus/rules/*.yaml  --(promtool check)-->
#   apps/astronomy-shop/values-slo-rules.yaml  (prometheus.serverFiles."recording_rules.yml")
#
# Requires only Docker. Usage: scripts/gen-slo-rules.sh   (or: make slo-rules)
set -euo pipefail
cd "$(dirname "$0")/.."

SLOTH_IMAGE="ghcr.io/slok/sloth:v0.16.0"
PROM_IMAGE="prom/prometheus:v3.14.0"   # same version as the bundled Prometheus
RULES_DIR="observability/prometheus/rules"
OUT_VALUES="apps/astronomy-shop/values-slo-rules.yaml"

mkdir -p "$RULES_DIR"
rm -f "$RULES_DIR"/*.yaml

echo "==> Generating rules with Sloth"
docker run --rm -v "$PWD:/w" -w /w "$SLOTH_IMAGE" generate -i slos -o "$RULES_DIR" --no-log

echo "==> Validating rules with promtool"
docker run --rm -v "$PWD/$RULES_DIR:/r" --entrypoint promtool "$PROM_IMAGE" \
  check rules $(cd "$RULES_DIR" && ls *.yaml | sed 's|^|/r/|')

echo "==> Packaging rules as Helm values -> $OUT_VALUES"
python3 - "$RULES_DIR" "$OUT_VALUES" <<'PY'
import glob, os, sys, yaml
rules_dir, out = sys.argv[1], sys.argv[2]
groups = []
for f in sorted(glob.glob(os.path.join(rules_dir, "*.yaml"))):
    for doc in yaml.safe_load_all(open(f)):
        if doc and "groups" in doc:
            groups.extend(doc["groups"])
values = {"prometheus": {"serverFiles": {"recording_rules.yml": {"groups": groups}}}}
with open(out, "w") as fh:
    fh.write("# GENERATED by scripts/gen-slo-rules.sh from slos/*.yaml. DO NOT EDIT.\n")
    fh.write("# Loaded by `make deploy` as an extra values file.\n")
    yaml.safe_dump(values, fh, sort_keys=False, width=200)
print(f"   {len(groups)} rule groups, {sum(len(g['rules']) for g in groups)} rules")
PY
