#!/usr/bin/env bash
# Generate observability/alerting/alertmanagerconfig-sink.yaml from the real AlertmanagerConfig:
# identical routes + inhibitions, but every receiver becomes a webhook to the in-cluster alert-sink.
# Lets you test the full alert path without PagerDuty/Slack credentials.  Usage: make alerting-sink
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
import yaml
cr = yaml.safe_load(open("observability/alerting/alertmanagerconfig.yaml"))
cr["metadata"]["name"] = "sre-lab-sink"
cr["spec"]["receivers"] = [
    {"name": r["name"]} if r["name"] == "null" else
    {"name": r["name"], "webhookConfigs": [{"url": f"http://alert-sink.observability:8080/{r['name']}", "sendResolved": True}]}
    for r in cr["spec"]["receivers"]]
with open("observability/alerting/alertmanagerconfig-sink.yaml", "w") as f:
    f.write("# GENERATED by scripts/gen-sink-alerting.sh from alertmanagerconfig.yaml. DO NOT EDIT.\n")
    f.write("# Same routing/inhibition as production; receivers replaced by the alert-sink webhook.\n")
    yaml.safe_dump(cr, f, sort_keys=False, width=200)
print("generated alertmanagerconfig-sink.yaml:", [r["name"] for r in cr["spec"]["receivers"]])
PY
